name: pubspec_checker
description: A simple Dart package that checks the compatibility of all dependencies in the pubspec.yaml file for specified platforms
version: 1.1.0
repository: https://github.com/marianz-bonfire/pubspec_checker
homepage: https://github.com/marianz-bonfire/pubspec_checker
issue_tracker: https://github.com/marianz-bonfire/pubspec_checker/issues

environment:
  sdk: ^3.2.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

dependencies:
  args: ^2.5.0
  html: ^0.15.5
  http: ^1.2.0
  yaml: ^3.1.2

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

topics:
  - tarsier
  - pubspec
  - checker
  - package
  - platforms
  - compatibility

screenshots:
  - description: The package logo.
    path: assets/logo.png